#!/bin/sh
echo "Let's calculate GCD of two values. Input the value."
read ans
a=$ans
echo "Your first value is: $a "
echo "Then, please type the second value."
read ans
b=$ans
echo "Your second value is: $b "
:
while [ $r -ne 1 ]
do
     if [ $b -ge $a ] | b="$a" && a="$b" ; then
r=$(( $a % $b )) ; a="$b" && b="$r" ;
fi
done
:
    if [ $r -eq 0 ] | echo "The GCM is: $a"
    then echo "Sorry, no GCM found"
fi
 
